In [2]:
import pandas as pd
import numpy as np

In [12]:
data1 = pd.read_csv('S.csv')
data2 = pd.read_csv('T.csv')
data = pd.concat([data1, data2])

In [13]:
newout = pd.DataFrame()
for choice, model in data.groupby(['Data', 'Scoretype', 'Method', 'NWEEKS']):
    if model['TP'].hasnans:
        continue
    tmp = pd.DataFrame({'Data': [choice[0]], 'Scoretype': [choice[1]], 'Method': [choice[2]], 
                        'NWEEKS': [choice[3]], 'fsval':[np.nan], 'r': [np.nan], 'TP': [model['TP'].mean()], 
                        'BFP': [model['BFP'].mean()], 'TP1': [model['TP1'].mean()], 
                        'TP2': [model['TP2'].mean()], 'BFP1': [model['BFP1'].mean()], 
                        'BFP2': [model['BFP2'].mean()]})
    newout = pd.concat([newout, tmp])

In [14]:
newout.index = range(len(newout))
newout.sort_values('TP', ascending = False).head(50)

,Data,Scoretype,Method,NWEEKS,fsval,r,TP,BFP,TP1,TP2,BFP1,BFP2
130,TS_S,2_2,A,11,NaN,NaN,0.408337,0.018006,0.149851,0.666822,0.000000,0.036012
42,SS_S,2_2,A,11,NaN,NaN,0.408337,0.018006,0.149851,0.666822,0.000000,0.036012
131,TS_S,2_2,A,12,NaN,NaN,0.407989,0.017274,0.154638,0.661339,0.000000,0.034548
43,SS_S,2_2,A,12,NaN,NaN,0.407989,0.017274,0.154638,0.661339,0.000000,0.034548
32,SS_S,2_2,-26,12,NaN,NaN,0.407914,0.015493,0.180373,0.635456,0.000000,0.030987
120,TS_S,2_2,-26,12,NaN,NaN,0.407914,0.015493,0.180373,0.635456,0.000000,0.030987
109,TS_S,2_1,A,12,NaN,NaN,0.407815,0.017809,0.159574,0.656057,0.000000,0.035618
21,SS_S,2_1,A,12,NaN,NaN,0.407815,0.017809,0.159574,0.656057,0.000000,0.035618
41,SS_S,2_2,A,10,NaN,NaN,0.407020,0.018397,0.148621,0.665420,0.000000,0.036793
129,TS_S,2_2,A,10,NaN,NaN,0.407020,0.018397,0.148621,0.665420,0.000000,0.036793
19,SS_S,2_1,A,10,NaN,NaN,0.405978,0.017892,0.150727,0.661229,0.000000,0.035783
107,TS_S,2_1,A,10,NaN,NaN,0.405978,0.017892,0.150727,0.661229,0.000000,0.035783
26,SS_S,2_2,-26,6,NaN,NaN,0.405746,0.013336,0.168496,0.642996,0.000000,0.026672
114,TS_S,2_2,-26,6,NaN,NaN,0.405746,0.013336,0.168496,0.642996,0.000000,0.026672
108,TS_S,2_1,A,11,NaN,NaN,0.405647,0.017498,0.151903,0.659392,0.000000,0.034997
20,SS_S,2_1,A,11,NaN,NaN,0.405647,0.017498,0.151903,0.659392,0.000000,0.034997
10,SS_S,2_1,-26,12,NaN,NaN,0.404491,0.013784,0.177038,0.631944,0.000000,0.027568
98,TS_S,2_1,-26,12,NaN,NaN,0.404491,0.013784,0.177038,0.631944,0.000000,0.027568
126,TS_S,2_2,A,7,NaN,NaN,0.404020,0.018654,0.143927,0.664114,0.000000,0.037308
38,SS_S,2_2,A,7,NaN,NaN,0.404020,0.018654,0.143927,0.664114,0.000000,0.037308
16,SS_S,2_1,A,7,NaN,NaN,0.404007,0.018654,0.144989,0.663024,0.000000,0.037308
104,TS_S,2_1,A,7,NaN,NaN,0.404007,0.018654,0.144989,0.663024,0.000000,0.037308
29,SS_S,2_2,-26,9,NaN,NaN,0.403597,0.012817,0.170360,0.636834,0.000000,0.025634
117,TS_S,2_2,-26,9,NaN,NaN,0.403597,0.012817,0.170360,0.636834,0.000000,0.025634
39,SS_S,2_2,A,8,NaN,NaN,0.403063,0.019948,0.144618,0.661507,0.000000,0.039896
127,TS_S,2_2,A,8,NaN,NaN,0.403063,0.019948,0.144618,0.661507,0.000000,0.039896
186,TT_T,2_1,-26,12,NaN,NaN,0.402908,0.015508,0.170385,0.635430,0.001724,0.029292
30,SS_S,2_2,-26,10,NaN,NaN,0.402467,0.014000,0.170037,0.634897,0.000000,0.028000
118,TS_S,2_2,-26,10,NaN,NaN,0.402467,0.014000,0.170037,0.634897,0.000000,0.028000
218,TT_T,2_2,A,11,NaN,NaN,0.401933,0.018070,0.141342,0.662524,0.003088,0.033052
31,SS_S,2_2,-26,11,NaN,NaN,0.401740,0.015212,0.169868,0.633612,0.000000,0.030425
119,TS_S,2_2,-26,11,NaN,NaN,0.401740,0.015212,0.169868,0.633612,0.000000,0.030425
219,TT_T,2_2,A,12,NaN,NaN,0.401551,0.017360,0.149626,0.653477,0.003159,0.031560
197,TT_T,2_1,A,12,NaN,NaN,0.401327,0.017885,0.149755,0.652899,0.004241,0.031529
128,TS_S,2_2,A,9,NaN,NaN,0.401181,0.019072,0.139816,0.662546,0.000000,0.038145
40,SS_S,2_2,A,9,NaN,NaN,0.401181,0.019072,0.139816,0.662546,0.000000,0.038145
207,TT_T,2_2,-26,11,NaN,NaN,0.400056,0.015990,0.163725,0.636388,0.001527,0.030454
9,SS_S,2_1,-26,11,NaN,NaN,0.400049,0.014358,0.168116,0.631982,0.000000,0.028715
97,TS_S,2_1,-26,11,NaN,NaN,0.400049,0.014358,0.168116,0.631982,0.000000,0.028715
105,TS_S,2_1,A,8,NaN,NaN,0.400046,0.018915,0.145699,0.654392,0.000000,0.037829
17,SS_S,2_1,A,8,NaN,NaN,0.400046,0.018915,0.145699,0.654392,0.000000,0.037829
196,TT_T,2_1,A,11,NaN,NaN,0.399966,0.018067,0.143473,0.656459,0.003088,0.033046
15,SS_S,2_1,A,6,NaN,NaN,0.399895,0.020552,0.138827,0.660962,0.000966,0.040138
103,TS_S,2_1,A,6,NaN,NaN,0.399895,0.020552,0.138827,0.660962,0.000966,0.040138
125,TS_S,2_2,A,6,NaN,NaN,0.399845,0.020522,0.138735,0.660955,0.000966,0.040077
37,SS_S,2_2,A,6,NaN,NaN,0.399845,0.020522,0.138735,0.660955,0.000966,0.040077
208,TT_T,2_2,-26,12,NaN,NaN,0.399688,0.016370,0.172110,0.627265,0.001724,0.031016
4,SS_S,2_1,-26,6,NaN,NaN,0.399044,0.012567,0.162533,0.635554,0.000000,0.025134
92,TS_S,2_1,-26,6,NaN,NaN,0.399044,0.012567,0.162533,0.635554,0.000000,0.025134
3,SS_S,2_1,-26,5,NaN,NaN,0.398428,0.014557,0.158271,0.638584,0.000000,0.029114

In [15]:
# for choice, model in newout.groupby(['TargetType', 'TargetMeth', 'Method', 'NWEEKS', 'fsval']):
#     model = model.sort_values('TP', ascending = False)
#     print(model)

In [16]:
# count = 0
# total = 0
# for choice, model in newout.groupby(['TargetType', 'TargetMeth', 'Method', 'r']):
#     total += 1
    
#     model = model.sort_values('TP', ascending = False)

#     model.index = range(len(model))
    
#     if model.loc[0]['NWEEKS'] >= 9:
#         count += 1

# print(count)
# print(total)

In [17]:
# total