In [3]:
import pandas as pd

In [4]:
data1 = pd.read_csv('S_D.csv')
data2 = pd.read_csv('QS_D.csv')
data = pd.concat([data1, data2])
data = data[data['r'] != 'r']

In [5]:
newout = pd.DataFrame()
for choice, model in data.groupby(['TargetType', 'TargetMeth', 'Method', 'NWEEKS', 'fsval', 'r']):
    if model['TP'].hasnans:
        continue
    tmp = pd.DataFrame({'TargetType': [choice[0]], 'TargetMeth': [choice[1]], 'Method': [choice[2]], 
                        'NWEEKS': [choice[3]], 'fsval':[choice[4]], 'r': [choice[5]], 'TP': [model['TP'].mean()], 
                        'BFP': [model['BFP'].mean()], 'TP1': [model['TP1'].mean()], 
                        'TP2': [model['TP2'].mean()], 'BFP1': [model['BFP1'].mean()], 
                        'BFP2': [model['BFP2'].mean()]})
    newout = pd.concat([newout, tmp])

In [7]:
newout.index = range(len(newout))
newout.sort_values('TP', ascending = False)

,TargetType,TargetMeth,Method,NWEEKS,fsval,r,TP,BFP,TP1,TP2,BFP1,BFP2
124,S,D,-26,12,0.4,1,0.457786,0.029157,0.244098,0.671475,0.001587,0.056728
119,S,D,-26,11,0.4,r2,0.457442,0.029602,0.241277,0.673608,0.001527,0.057677
118,S,D,-26,11,0.4,1,0.457365,0.029602,0.239596,0.675134,0.001527,0.057677
125,S,D,-26,12,0.4,r2,0.456138,0.029157,0.240801,0.671475,0.001587,0.056728
112,S,D,-26,10,0.4,1,0.453837,0.029961,0.236405,0.671269,0.001575,0.058347
...,...,...,...,...,...,...,...,...,...,...,...,...
15,QS,D,-26,8,0.3,r2,0.408090,0.045252,0.195388,0.620791,0.030872,0.059632
30,QS,D,-26,12,0.3,1,0.407771,0.036113,0.209509,0.606032,0.027912,0.044315
31,QS,D,-26,12,0.3,r2,0.407771,0.036113,0.209509,0.606032,0.027912,0.044315
19,QS,D,-26,9,0.3,r2,0.405091,0.040651,0.195505,0.614678,0.026858,0.054443
18,QS,D,-26,9,0.3,1,0.405091,0.040651,0.195505,0.614678,0.026858,0.054443

In [1]:
# for choice, model in newout.groupby(['TargetType', 'TargetMeth', 'Method', 'NWEEKS', 'fsval']):
#     model = model.sort_values('TP', ascending = False)
#     print(model)

In [2]:
# count = 0
# total = 0
# for choice, model in newout.groupby(['TargetType', 'TargetMeth', 'Method', 'r']):
#     total += 1
    
#     model = model.sort_values('TP', ascending = False)

#     model.index = range(len(model))
    
#     if model.loc[0]['NWEEKS'] >= 9:
#         count += 1

# print(count)
# print(total)

In [3]:
# total